//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaneKsiązek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazki
    {
        public int ksiazkaID { get; set; }
        public string Autor { get; set; }
        public string Tytuł { get; set; }
        public Nullable<int> LiczbaStron { get; set; }
    }
}
