/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 10-Apr-2019 01:41:37 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Bilet_jest kupowany]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Bilet] DROP CONSTRAINT [FK_Bilet_jest kupowany]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Eksponat_eksponaty do wystawienia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Eksponat] DROP CONSTRAINT [FK_Eksponat_eksponaty do wystawienia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Eksponat_jest ustawiany]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Eksponat] DROP CONSTRAINT [FK_Eksponat_jest ustawiany]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Klient_zleca]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Klient] DROP CONSTRAINT [FK_Klient_zleca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PBiurowy_Pracownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pbiurowy] DROP CONSTRAINT [FK_PBiurowy_Pracownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Wystawa_wymaga biletu]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Wystawa] DROP CONSTRAINT [FK_Wystawa_wymaga biletu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Wystawa_jest wyprawiana]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Wystawa] DROP CONSTRAINT [FK_Wystawa_jest wyprawiana]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Bilet]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Bilet]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Eksponat]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Eksponat]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Gosc]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Gosc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Klient]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Klient]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pbiurowy]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pbiurowy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pracownik]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pracownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Wystawa]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Wystawa]
GO

/* Create Tables */

CREATE TABLE [Bilet]
(
	[Typ] char(10) NULL,
	[Cena] float NULL,
	[BiletID] int NOT NULL,
	[kupuje] int NOT NULL
)
GO

CREATE TABLE [Eksponat]
(
	[Nazwa] char(10) NULL,
	[Stanowisko] char(10) NULL,
	[EksponatID] int NOT NULL,
	[wystawia eksponaty] int NULL,
	[ustawia eksponaty] int NOT NULL
)
GO

CREATE TABLE [Gosc]
(
	[Typgoscia] char(10) NULL,
	[GoscID] int NOT NULL
)
GO

CREATE TABLE [Klient]
(
	[Imie] char(10) NULL,
	[Nazwisko] char(10) NULL,
	[Miejscezamieszkania] char(10) NULL,
	[Nrtelefonu] int NULL,
	[KlientID] int NOT NULL,
	[jest zlecana] int NOT NULL
)
GO

CREATE TABLE [Pbiurowy]
(
	[PbiurowyID] int NOT NULL
)
GO

CREATE TABLE [Pracownik]
(
	[Imie] char(10) NULL,
	[Nazwisko] char(10) NULL,
	[Miejscezamieszkania] char(10) NULL,
	[Nrtelefonu] char(10) NULL,
	[PracownikID] int NOT NULL
)
GO

CREATE TABLE [Wystawa]
(
	[Liczbaeksponatow] int NULL,
	[Liczbagosci] int NULL,
	[Nazwawystawy] char(10) NULL,
	[Typwystawy] char(10) NULL,
	[Datarozpoczecia] char(10) NULL,
	[Godzinarozpoczecia] int NULL,
	[Czastrwania] int NULL,
	[WystawaID] int NOT NULL,
	[wstęp na wystawę] int NOT NULL,
	[uczestniczy w wystawie] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Bilet] 
 ADD CONSTRAINT [PK_Bilet]
	PRIMARY KEY CLUSTERED ([BiletID] ASC)
GO

ALTER TABLE [Eksponat] 
 ADD CONSTRAINT [PK_Eksponat]
	PRIMARY KEY CLUSTERED ([EksponatID] ASC)
GO

ALTER TABLE [Gosc] 
 ADD CONSTRAINT [PK_Gosc]
	PRIMARY KEY CLUSTERED ([GoscID] ASC)
GO

ALTER TABLE [Klient] 
 ADD CONSTRAINT [PK_Klient]
	PRIMARY KEY CLUSTERED ([KlientID] ASC)
GO

ALTER TABLE [Pbiurowy] 
 ADD CONSTRAINT [PK_Pbiurowy]
	PRIMARY KEY CLUSTERED ([PbiurowyID] ASC)
GO

ALTER TABLE [Pracownik] 
 ADD CONSTRAINT [PK_Pracownik]
	PRIMARY KEY CLUSTERED ([PracownikID] ASC)
GO

ALTER TABLE [Wystawa] 
 ADD CONSTRAINT [PK_Wystawa]
	PRIMARY KEY CLUSTERED ([WystawaID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Bilet] ADD CONSTRAINT [FK_Bilet_jest kupowany]
	FOREIGN KEY ([GoscID]) REFERENCES [Gosc] ([GoscID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Eksponat] ADD CONSTRAINT [FK_Eksponat_eksponaty do wystawienia]
	FOREIGN KEY ([WystawaID]) REFERENCES [Wystawa] ([WystawaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Eksponat] ADD CONSTRAINT [FK_Eksponat_jest ustawiany]
	FOREIGN KEY ([KplacowkiID]) REFERENCES [Kplacowki] ([KplacowkiID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Klient] ADD CONSTRAINT [FK_Klient_zleca]
	FOREIGN KEY ([WystawaID]) REFERENCES [Wystawa] ([WystawaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pbiurowy] ADD CONSTRAINT [FK_PBiurowy_Pracownik]
	FOREIGN KEY ([PbiurowyID]) REFERENCES [Pracownik] ([PracownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Wystawa] ADD CONSTRAINT [FK_Wystawa_wymaga biletu]
	FOREIGN KEY ([BiletID]) REFERENCES [Bilet] ([BiletID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Wystawa] ADD CONSTRAINT [FK_Wystawa_jest wyprawiana]
	FOREIGN KEY ([GoscID]) REFERENCES [Gosc] ([GoscID]) ON DELETE No Action ON UPDATE No Action
GO
