/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 10-Apr-2019 00:21:17 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Bilet_jest kupowany]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Bilet] DROP CONSTRAINT [FK_Bilet_jest kupowany]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Eksponat_eksponaty do wystawienia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Eksponat] DROP CONSTRAINT [FK_Eksponat_eksponaty do wystawienia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Eksponat_jest ustawiany]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Eksponat] DROP CONSTRAINT [FK_Eksponat_jest ustawiany]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Grafik_jest ustalany]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Grafik] DROP CONSTRAINT [FK_Grafik_jest ustalany]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KBiura_Kierownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kbiura] DROP CONSTRAINT [FK_KBiura_Kierownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Kierownik_Pracownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kierownik] DROP CONSTRAINT [FK_Kierownik_Pracownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KierownikWystawa_jest wykorzystywana]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [KierownikWystawa] DROP CONSTRAINT [FK_KierownikWystawa_jest wykorzystywana]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KierownikWystawa_wykorzystuje do organizacji]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [KierownikWystawa] DROP CONSTRAINT [FK_KierownikWystawa_wykorzystuje do organizacji]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Klient_zleca]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Klient] DROP CONSTRAINT [FK_Klient_zleca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KOchrony_Kierownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kochrony] DROP CONSTRAINT [FK_KOchrony_Kierownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KOchrony_odczytuje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kochrony] DROP CONSTRAINT [FK_KOchrony_odczytuje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KPlacowki_Kierownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kplacowki] DROP CONSTRAINT [FK_KPlacowki_Kierownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PBiurowy_Pracownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pbiurowy] DROP CONSTRAINT [FK_PBiurowy_Pracownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pochrony_Raport]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pochrony] DROP CONSTRAINT [FK_Pochrony_Raport]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_POchrony_Pracownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pochrony] DROP CONSTRAINT [FK_POchrony_Pracownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PPorzadkowy_Pracownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pporzadkowy] DROP CONSTRAINT [FK_PPorzadkowy_Pracownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Wystawa_wymaga biletu]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Wystawa] DROP CONSTRAINT [FK_Wystawa_wymaga biletu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Wystawa_jest wyprawiana]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Wystawa] DROP CONSTRAINT [FK_Wystawa_jest wyprawiana]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PracownikGrafik_Grafik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ZmianaPracownika] DROP CONSTRAINT [FK_PracownikGrafik_Grafik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PracownikGrafik_Pracownik]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ZmianaPracownika] DROP CONSTRAINT [FK_PracownikGrafik_Pracownik]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Bilet]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Bilet]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Eksponat]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Eksponat]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Gosc]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Gosc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Grafik]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Grafik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kbiura]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kbiura]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kierownik]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kierownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[KierownikWystawa]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [KierownikWystawa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Klient]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Klient]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kochrony]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kochrony]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kplacowki]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kplacowki]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pbiurowy]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pbiurowy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pochrony]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pochrony]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pporzadkowy]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pporzadkowy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pracownik]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pracownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Raport]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Raport]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Wystawa]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Wystawa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ZmianaPracownika]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ZmianaPracownika]
GO

/* Create Tables */

CREATE TABLE [Bilet]
(
	[Typ] char(10) NULL,
	[Cena] float NULL,
	[BiletID] int NOT NULL,
	[kupuje] int NOT NULL
)
GO

CREATE TABLE [Eksponat]
(
	[Nazwa] char(10) NULL,
	[Stanowisko] char(10) NULL,
	[EksponatID] int NOT NULL,
	[wystawia eksponaty] int NULL,
	[ustawia eksponaty] int NOT NULL
)
GO

CREATE TABLE [Gosc]
(
	[Typgoscia] char(10) NULL,
	[GoscID] int NOT NULL
)
GO

CREATE TABLE [Grafik]
(
	[Data] char(10) NULL,
	[Startzmiany] char(10) NULL,
	[GrafikID] int NOT NULL,
	[ustala grafik] int NULL
)
GO

CREATE TABLE [Kbiura]
(
	[KbiuraID] int NOT NULL
)
GO

CREATE TABLE [Kierownik]
(
	[KierownikID] int NOT NULL
)
GO

CREATE TABLE [KierownikWystawa]
(
	[jest wykorzystywana] int NULL,
	[wykorzystuje do organizacji] int NULL
)
GO

CREATE TABLE [Klient]
(
	[Imie] char(10) NULL,
	[Nazwisko] char(10) NULL,
	[Miejscezamieszkania] char(10) NULL,
	[Nrtelefonu] int NULL,
	[KlientID] int NOT NULL,
	[jest zlecana] int NOT NULL
)
GO

CREATE TABLE [Kochrony]
(
	[KochronyID] int NOT NULL,
	[jest odczytywany] int NOT NULL
)
GO

CREATE TABLE [Kplacowki]
(
	[KplacowkiID] int NOT NULL
)
GO

CREATE TABLE [Pbiurowy]
(
	[PbiurowyID] int NOT NULL
)
GO

CREATE TABLE [Pochrony]
(
	[PochronyID] int NOT NULL,
	[RaportID] int NULL
)
GO

CREATE TABLE [Pporzadkowy]
(
	[PporzadkowyID] int NOT NULL
)
GO

CREATE TABLE [Pracownik]
(
	[Imie] char(10) NULL,
	[Nazwisko] char(10) NULL,
	[Miejscezamieszkania] char(10) NULL,
	[Nrtelefonu] char(10) NULL,
	[PracownikID] int NOT NULL
)
GO

CREATE TABLE [Raport]
(
	[Raport] char(10) NULL,
	[PochronyID] int NOT NULL,
	[RaportID] int NOT NULL
)
GO

CREATE TABLE [Wystawa]
(
	[Liczbaeksponatow] int NULL,
	[Liczbagosci] int NULL,
	[Nazwawystawy] char(10) NULL,
	[Typwystawy] char(10) NULL,
	[Datarozpoczecia] char(10) NULL,
	[Godzinarozpoczecia] int NULL,
	[Czastrwania] int NULL,
	[WystawaID] int NOT NULL,
	[wstęp na wystawę] int NOT NULL,
	[uczestniczy w wystawie] int NOT NULL
)
GO

CREATE TABLE [ZmianaPracownika]
(
	[GrafikID] int NULL,
	[PracownikID] int NULL,
	[ZmianaID] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Bilet] 
 ADD CONSTRAINT [PK_Bilet]
	PRIMARY KEY CLUSTERED ([BiletID] ASC)
GO

ALTER TABLE [Eksponat] 
 ADD CONSTRAINT [PK_Eksponat]
	PRIMARY KEY CLUSTERED ([EksponatID] ASC)
GO

ALTER TABLE [Gosc] 
 ADD CONSTRAINT [PK_Gosc]
	PRIMARY KEY CLUSTERED ([GoscID] ASC)
GO

ALTER TABLE [Grafik] 
 ADD CONSTRAINT [PK_Grafik]
	PRIMARY KEY CLUSTERED ([GrafikID] ASC)
GO

ALTER TABLE [Kbiura] 
 ADD CONSTRAINT [PK_Kbiura]
	PRIMARY KEY CLUSTERED ([KbiuraID] ASC)
GO

ALTER TABLE [Kierownik] 
 ADD CONSTRAINT [PK_Kierownik]
	PRIMARY KEY CLUSTERED ([KierownikID] ASC)
GO

ALTER TABLE [Klient] 
 ADD CONSTRAINT [PK_Klient]
	PRIMARY KEY CLUSTERED ([KlientID] ASC)
GO

ALTER TABLE [Kochrony] 
 ADD CONSTRAINT [PK_Kochrony]
	PRIMARY KEY CLUSTERED ([KochronyID] ASC)
GO

ALTER TABLE [Kplacowki] 
 ADD CONSTRAINT [PK_Kplacowki]
	PRIMARY KEY CLUSTERED ([KplacowkiID] ASC)
GO

ALTER TABLE [Pbiurowy] 
 ADD CONSTRAINT [PK_Pbiurowy]
	PRIMARY KEY CLUSTERED ([PbiurowyID] ASC)
GO

ALTER TABLE [Pochrony] 
 ADD CONSTRAINT [PK_Pochrony]
	PRIMARY KEY CLUSTERED ([PochronyID] ASC)
GO

ALTER TABLE [Pporzadkowy] 
 ADD CONSTRAINT [PK_Pporzadkowy]
	PRIMARY KEY CLUSTERED ([PporzadkowyID] ASC)
GO

ALTER TABLE [Pracownik] 
 ADD CONSTRAINT [PK_Pracownik]
	PRIMARY KEY CLUSTERED ([PracownikID] ASC)
GO

ALTER TABLE [Raport] 
 ADD CONSTRAINT [PK_Raport]
	PRIMARY KEY CLUSTERED ([RaportID] ASC)
GO

ALTER TABLE [Wystawa] 
 ADD CONSTRAINT [PK_Wystawa]
	PRIMARY KEY CLUSTERED ([WystawaID] ASC)
GO

ALTER TABLE [ZmianaPracownika] 
 ADD CONSTRAINT [PK_ZmianaPracownika]
	PRIMARY KEY CLUSTERED ([ZmianaID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Bilet] ADD CONSTRAINT [FK_Bilet_jest kupowany]
	FOREIGN KEY ([kupuje]) REFERENCES [Gosc] ([GoscID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Eksponat] ADD CONSTRAINT [FK_Eksponat_eksponaty do wystawienia]
	FOREIGN KEY ([wystawia eksponaty]) REFERENCES [Wystawa] ([WystawaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Eksponat] ADD CONSTRAINT [FK_Eksponat_jest ustawiany]
	FOREIGN KEY ([ustawia eksponaty]) REFERENCES [Kplacowki] ([KplacowkiID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Grafik] ADD CONSTRAINT [FK_Grafik_jest ustalany]
	FOREIGN KEY ([ustala grafik]) REFERENCES [Kierownik] ([KierownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kbiura] ADD CONSTRAINT [FK_KBiura_Kierownik]
	FOREIGN KEY ([KbiuraID]) REFERENCES [Kierownik] ([KierownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kierownik] ADD CONSTRAINT [FK_Kierownik_Pracownik]
	FOREIGN KEY ([KierownikID]) REFERENCES [Pracownik] ([PracownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [KierownikWystawa] ADD CONSTRAINT [FK_KierownikWystawa_jest wykorzystywana]
	FOREIGN KEY ([jest wykorzystywana]) REFERENCES [Wystawa] ([WystawaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [KierownikWystawa] ADD CONSTRAINT [FK_KierownikWystawa_wykorzystuje do organizacji]
	FOREIGN KEY ([wykorzystuje do organizacji]) REFERENCES [Kierownik] ([KierownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Klient] ADD CONSTRAINT [FK_Klient_zleca]
	FOREIGN KEY ([jest zlecana]) REFERENCES [Wystawa] ([WystawaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kochrony] ADD CONSTRAINT [FK_KOchrony_Kierownik]
	FOREIGN KEY ([KochronyID]) REFERENCES [Kierownik] ([KierownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kochrony] ADD CONSTRAINT [FK_KOchrony_odczytuje]
	FOREIGN KEY ([jest odczytywany]) REFERENCES [Raport] ([RaportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kplacowki] ADD CONSTRAINT [FK_KPlacowki_Kierownik]
	FOREIGN KEY ([KplacowkiID]) REFERENCES [Kierownik] ([KierownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pbiurowy] ADD CONSTRAINT [FK_PBiurowy_Pracownik]
	FOREIGN KEY ([PbiurowyID]) REFERENCES [Pracownik] ([PracownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pochrony] ADD CONSTRAINT [FK_Pochrony_Raport]
	FOREIGN KEY ([RaportID]) REFERENCES [Raport] ([RaportID])
GO

ALTER TABLE [Pochrony] ADD CONSTRAINT [FK_POchrony_Pracownik]
	FOREIGN KEY ([PochronyID]) REFERENCES [Pracownik] ([PracownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pporzadkowy] ADD CONSTRAINT [FK_PPorzadkowy_Pracownik]
	FOREIGN KEY ([PporzadkowyID]) REFERENCES [Pracownik] ([PracownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Wystawa] ADD CONSTRAINT [FK_Wystawa_wymaga biletu]
	FOREIGN KEY ([wstęp na wystawę]) REFERENCES [Bilet] ([BiletID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Wystawa] ADD CONSTRAINT [FK_Wystawa_jest wyprawiana]
	FOREIGN KEY ([uczestniczy w wystawie]) REFERENCES [Gosc] ([GoscID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ZmianaPracownika] ADD CONSTRAINT [FK_PracownikGrafik_Grafik]
	FOREIGN KEY ([GrafikID]) REFERENCES [Grafik] ([GrafikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ZmianaPracownika] ADD CONSTRAINT [FK_PracownikGrafik_Pracownik]
	FOREIGN KEY ([PracownikID]) REFERENCES [Pracownik] ([PracownikID]) ON DELETE No Action ON UPDATE No Action
GO
